from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel, Field, ValidationError

from app.reasoning.llm import reasoning_llm


class SummaryResponse(BaseModel):
    """
    Structured summary returned by the reasoning layer.
    """

    summary: str = Field(
        ...,
        min_length=1,
        description="Concise evidence-based summary."
    )


class SummarizationError(Exception):
    """Raised when summarization fails."""


class Summarizer:
    """
    Generate an evidence-based summary from deterministic
    extraction results.

    The LLM is only responsible for semantic summarization.
    It must not invent facts that are absent from the evidence.
    """

    SYSTEM_PROMPT = """
You are the summarization component of a Universal AI Media
Processing Pipeline.

Your task is to summarize the provided deterministic evidence.

Strict rules:

1. Use ONLY information present in the provided evidence.
2. Do NOT invent facts, entities, events, dates, timestamps,
   speakers, pages, or other information.
3. Do NOT infer unsupported details.
4. Preserve important facts from the evidence.
5. Remove unnecessary repetition.
6. Keep the summary concise but informative.
7. Do not mention information that is not supported by the evidence.
8. Return ONLY valid JSON.
9. Do not use Markdown code fences.
10. Do not include commentary outside the JSON.

Required JSON format:

{
  "summary": "Concise evidence-based summary."
}
""".strip()

    def summarize(
        self,
        evidence: list[dict[str, Any]],
    ) -> SummaryResponse:
        """
        Generate a summary from structured deterministic evidence.

        Parameters
        ----------
        evidence:
            Evidence generated by deterministic processors.

        Returns
        -------
        SummaryResponse
            Validated summary.

        Raises
        ------
        SummarizationError
            If the LLM fails or returns invalid structured output.
        """

        if not evidence:
            return SummaryResponse(
                summary="No evidence was available for summarization."
            )

        prompt = self._build_prompt(evidence)

        try:
            response = reasoning_llm.generate(
                prompt,
                system_prompt=self.SYSTEM_PROMPT,
                temperature=0.1,
            )

        except Exception as exc:
            raise SummarizationError(
                f"Summarization failed: {exc}"
            ) from exc

        return self._parse_response(response)

    @staticmethod
    def _build_prompt(
        evidence: list[dict[str, Any]],
    ) -> str:
        """
        Build an evidence-only prompt for the LLM.
        """

        evidence_json = json.dumps(
            evidence,
            ensure_ascii=False,
            indent=2,
            default=str,
        )

        return f"""
Create a concise summary of the following
deterministically extracted evidence.

Use only the information provided.

EVIDENCE:
{evidence_json}

Return the required JSON structure only.
""".strip()

    @staticmethod
    def _parse_response(
        response: str,
    ) -> SummaryResponse:
        """
        Parse and validate the LLM JSON response.
        """

        cleaned = response.strip()

        # Remove accidental Markdown code fences.
        if cleaned.startswith("```"):
            lines = cleaned.splitlines()

            if lines and lines[0].startswith("```"):
                lines = lines[1:]

            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]

            cleaned = "\n".join(lines).strip()

        try:
            data = json.loads(cleaned)

        except json.JSONDecodeError as exc:
            raise SummarizationError(
                "LLM returned invalid JSON for summarization."
            ) from exc

        try:
            return SummaryResponse.model_validate(data)

        except ValidationError as exc:
            raise SummarizationError(
                f"LLM summary response failed schema validation: {exc}"
            ) from exc


# Shared summarizer.
summarizer = Summarizer()

