from __future__ import annotations

import json
from typing import Any

from pydantic import BaseModel, Field, ValidationError

from app.reasoning.llm import reasoning_llm


class Topic(BaseModel):
    """
    A semantic topic identified from extracted media evidence.
    """

    name: str = Field(
        ...,
        min_length=1,
        description="Short name of the topic."
    )

    description: str = Field(
        ...,
        min_length=1,
        description="Brief description based only on the evidence."
    )


class TopicsResponse(BaseModel):
    """
    Structured output returned by the topic reasoning layer.
    """

    topics: list[Topic] = Field(
        default_factory=list
    )


class TopicExtractionError(Exception):
    """Raised when topic extraction fails."""


class TopicExtractor:
    """
    Extract semantic topics from deterministic extraction evidence.

    The LLM is only responsible for semantic interpretation.
    It must not create facts that are absent from the evidence.
    """

    SYSTEM_PROMPT = """
You are the topic extraction component of a Universal AI Media
Processing Pipeline.

Your task is to identify the main semantic topics present in the
provided evidence.

Strict rules:

1. Use ONLY information present in the provided evidence.
2. Do NOT invent facts, entities, events, dates, timestamps,
   speakers, pages, or other information.
3. Do NOT infer unsupported details.
4. Topics should describe what the evidence is actually about.
5. Keep topic names short and meaningful.
6. Provide a brief description for each topic.
7. Return ONLY valid JSON.
8. Do not use Markdown code fences.
9. Do not include commentary outside the JSON.

Required JSON format:

{
  "topics": [
    {
      "name": "Topic name",
      "description": "Brief evidence-based description"
    }
  ]
}
""".strip()

    def extract(
        self,
        evidence: list[dict[str, Any]],
    ) -> TopicsResponse:
        """
        Extract topics from structured deterministic evidence.

        Parameters
        ----------
        evidence:
            Evidence generated by deterministic processors.

        Returns
        -------
        TopicsResponse
            Validated list of semantic topics.

        Raises
        ------
        TopicExtractionError
            If the LLM fails or returns invalid structured output.
        """

        if not evidence:
            return TopicsResponse(topics=[])

        prompt = self._build_prompt(evidence)

        try:
            response = reasoning_llm.generate(
                prompt,
                system_prompt=self.SYSTEM_PROMPT,
                temperature=0.1,
            )

        except Exception as exc:
            raise TopicExtractionError(
                f"Topic extraction failed: {exc}"
            ) from exc

        return self._parse_response(response)

    @staticmethod
    def _build_prompt(
        evidence: list[dict[str, Any]],
    ) -> str:
        """
        Build a compact evidence-only prompt for the LLM.
        """

        evidence_json = json.dumps(
            evidence,
            ensure_ascii=False,
            indent=2,
            default=str,
        )

        return f"""
Identify the main semantic topics contained in the following
deterministically extracted evidence.

Do not use any information other than this evidence.

EVIDENCE:
{evidence_json}

Return the required JSON structure only.
""".strip()

    @staticmethod
    def _parse_response(
        response: str,
    ) -> TopicsResponse:
        """
        Parse and validate the LLM JSON response.
        """

        cleaned = response.strip()

        # Remove accidental Markdown code fences.
        if cleaned.startswith("```"):
            lines = cleaned.splitlines()

            if lines and lines[0].startswith("```"):
                lines = lines[1:]

            if lines and lines[-1].strip() == "```":
                lines = lines[:-1]

            cleaned = "\n".join(lines).strip()

        try:
            data = json.loads(cleaned)

        except json.JSONDecodeError as exc:
            raise TopicExtractionError(
                "LLM returned invalid JSON for topic extraction."
            ) from exc

        try:
            return TopicsResponse.model_validate(data)

        except ValidationError as exc:
            raise TopicExtractionError(
                f"LLM topic response failed schema validation: {exc}"
            ) from exc


# Shared topic extractor.
topic_extractor = TopicExtractor()

